# requires 'DBI';
requires 'Mason';
requires 'Plack';
# requires 'Plack::Session::Store::Cache';
requires 'Plack::Middleware::Session';
requires 'Plack::Session::Store::DBI';
requires 'CGI';
# requires 'Log::Log4perl';
requires 'CHI';
# requires 'DBD::mysql';
requires 'DBIx::Connector';
# requires 'DBIx::Connector::Driver::mysql';